tryItOut("try{d}catch(__count__){const __count__=3}")